config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"]}
  validates :phone_number, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>All restaurants</h1>

<% @restaurants.each do |restaurant| %>
<ul>
  <li><%= restaurant.name %></li>
  <li><%= restaurant.address %></li>
</ul>
<% end %>

app/views/restaurants/new.html.erb
<h1>Add a new restaurant</h1>

<%= simple_form_for @restaurant do |f| %>
<%= f.input :name, label:"Restaurant name" %>
<%= f.input :address, label:"Address" %>
<%= f.input :phone_number, label:"Phone Number" %>
<%= f.input :category, label:"Category", collection:["chinese", "italian", "japanese", "french", "belgian"] %>
<%= f.button :submit %>
<% end %>

app/views/restaurants/show.html.erb
<h1>Here's your restaurant</h1>
<p><%= @restaurant.name %></p>
<p><%= @restaurant.address %></p>
<br>
<%= link_to "see all", restaurants_path %>